---
title: "salmon_group25"
author: "Laurel Wee, Cali Pfleger, Carmen Galaz-García"
date: "1/29/2021"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(tsibble) # time series tibbles
library(feasts)
library(patchwork)
```

### Overview

- picture
- Summary
- map

## Data Citation

```{r, basic data set, warning=FALSE}
fish <- read_csv(here("data","willamette_fish_passage.csv")) %>% 
  clean_names() %>% 
  select(date,steelhead,coho,jack_coho) %>% 
  mutate(date = lubridate::mdy(date)) %>%     # convert to date type
  rename(jack = jack_coho) %>%                # update column name
  pivot_longer(cols = steelhead:jack,         # convert to tidy data
               names_to="fish_type", 
               values_to = "n_crossing") %>% 
  as_tsibble(key=fish_type, index= date)           # convert date into tsibble
```


## Willametter Falls fish passage {.tabset}


### Original time series
```{r, tab 1}

```

### Seasonplots
```{r, tab 2}

basic_seasonplot <- function(fish_data, fish_type_str){
  month_fish_plot <- fish_data %>% 
    filter(fish_type == fish_type_str) %>%  
    index_by(yr_mo = ~yearmonth(.)) %>% # group by year and month
    summarize(monthly_mean_crossings = mean(n_crossing, na.rm=TRUE))  %>% 
    gg_season(y=monthly_mean_crossings) +
    labs(x=" ",
         y="average monthly passage")+
    theme_light()
  
  return(month_fish_plot)
}

steel_season <- basic_seasonplot(fish, "steelhead")+
  labs(title = "Steelhead Adult Passage (Jan-Dec)")+
  theme(legend.position = "none")

jack_season <- basic_seasonplot(fish, "jack") +
  labs(title = "Jack-Coho Adult Passage (Aug-Dec)")+
  theme(legend.position = "none")

coho_season <- basic_seasonplot(fish, "coho") +
  labs(title = "Coho Adult Passage (Aug-Dec)")+
  theme(legend.position = "none")


( coho_season| jack_season) / steel_season
```

### Annual counts by species
```{r, tab 3}

```

```{r}

fish %>% 
  filter(fish_type=="steelhead") %>% 
  index_by(yr_mo = ~yearmonth(.)) %>% # group by year and month
  summarize(monthly_mean_crossings = mean(n_crossing, na.rm=TRUE))  %>% 
  gg_season(y=monthly_mean_crossings)
```

